version: "3.8"

services:
  mongo_primary:
    container_name: mongo_primary
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB port to the host
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo_primary:/data/db

  mongo_secondary:
    container_name: mongo_secondary
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017" # Expose another port for secondary
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo_secondary:/data/db

  mongo_arbiter:
    container_name: mongo_arbiter
    image: mongo:latest
    restart: always
    ports:
      - "27019:27017" # Expose another port for arbiter
    command: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - mongo_arbiter:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo_primary:27017/status-update-app
      PORT: 5000
      SECRET_KEY: 2a4fc233cc5e9aa99b9d092c391c4fdff3247646f4f355e8483df3a66a342511e63ff358ff0f135d9754b30ff6d51271c4941e149d28838469eb233c19f9553a
      NODE_ENV: production
      CLIENT_ORIGIN: http://localhost:3000
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: supersecretpassword
    depends_on:
      - mongo_primary
      - mongo_secondary
      - mongo_arbiter

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  mongo_primary:
  mongo_secondary:
  mongo_arbiter:
